// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXHEhVwylUXU1SaIAfCdjFzChxMNcRJ2k',
    appId: '1:306555537542:web:6a8a823497b49f73b86907',
    messagingSenderId: '306555537542',
    projectId: 'authentificationflutter-9a1be',
    authDomain: 'authentificationflutter-9a1be.firebaseapp.com',
    storageBucket: 'authentificationflutter-9a1be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAeiKdlcJB28VX-d-12ttU9dVr9c3mfl8',
    appId: '1:306555537542:android:2007146ad57d3f45b86907',
    messagingSenderId: '306555537542',
    projectId: 'authentificationflutter-9a1be',
    storageBucket: 'authentificationflutter-9a1be.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXHEhVwylUXU1SaIAfCdjFzChxMNcRJ2k',
    appId: '1:306555537542:web:b5a38669a0a763e6b86907',
    messagingSenderId: '306555537542',
    projectId: 'authentificationflutter-9a1be',
    authDomain: 'authentificationflutter-9a1be.firebaseapp.com',
    storageBucket: 'authentificationflutter-9a1be.firebasestorage.app',
  );
}
